/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GridLayout {
    }
    interface HomeLayout {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PostDetail {
        "post": Object;
    }
    interface PostDetailComments {
        "commentDate": string;
        "comments": Object[];
    }
}
declare global {
    interface HTMLGridLayoutElement extends Components.GridLayout, HTMLStencilElement {
    }
    var HTMLGridLayoutElement: {
        prototype: HTMLGridLayoutElement;
        new (): HTMLGridLayoutElement;
    };
    interface HTMLHomeLayoutElement extends Components.HomeLayout, HTMLStencilElement {
    }
    var HTMLHomeLayoutElement: {
        prototype: HTMLHomeLayoutElement;
        new (): HTMLHomeLayoutElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPostDetailElement extends Components.PostDetail, HTMLStencilElement {
    }
    var HTMLPostDetailElement: {
        prototype: HTMLPostDetailElement;
        new (): HTMLPostDetailElement;
    };
    interface HTMLPostDetailCommentsElement extends Components.PostDetailComments, HTMLStencilElement {
    }
    var HTMLPostDetailCommentsElement: {
        prototype: HTMLPostDetailCommentsElement;
        new (): HTMLPostDetailCommentsElement;
    };
    interface HTMLElementTagNameMap {
        "grid-layout": HTMLGridLayoutElement;
        "home-layout": HTMLHomeLayoutElement;
        "my-component": HTMLMyComponentElement;
        "post-detail": HTMLPostDetailElement;
        "post-detail-comments": HTMLPostDetailCommentsElement;
    }
}
declare namespace LocalJSX {
    interface GridLayout {
    }
    interface HomeLayout {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PostDetail {
        "post"?: Object;
    }
    interface PostDetailComments {
        "commentDate"?: string;
        "comments"?: Object[];
    }
    interface IntrinsicElements {
        "grid-layout": GridLayout;
        "home-layout": HomeLayout;
        "my-component": MyComponent;
        "post-detail": PostDetail;
        "post-detail-comments": PostDetailComments;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "grid-layout": LocalJSX.GridLayout & JSXBase.HTMLAttributes<HTMLGridLayoutElement>;
            "home-layout": LocalJSX.HomeLayout & JSXBase.HTMLAttributes<HTMLHomeLayoutElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "post-detail": LocalJSX.PostDetail & JSXBase.HTMLAttributes<HTMLPostDetailElement>;
            "post-detail-comments": LocalJSX.PostDetailComments & JSXBase.HTMLAttributes<HTMLPostDetailCommentsElement>;
        }
    }
}
